import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faAnchor,
  faBicycle,
  faBug,
  faCar,
  faCloud,
  faCoffee,
  faFaceSmile,
  faFlask,
  faFutbol,
  faHandSpock,
  faHouse,
  faMicrophone,
  faMobile,
  faMoon,
  faSnowflake,
  faSun,
  faTree,
  faTurkishLiraSign,
} from "@fortawesome/free-solid-svg-icons";

export const numbers = [
  { number: 1 },
  { number: 2 },
  { number: 3 },
  { number: 4 },
  { number: 5 },
  { number: 6 },
  { number: 7 },
  { number: 8 },
  { number: 9 },
  { number: 10 },
  { number: 11 },
  { number: 12 },
  { number: 13 },
  { number: 14 },
  { number: 15 },
  { number: 16 },
  { number: 17 },
  { number: 18 },
];

export const icons = [
  { icon: <FontAwesomeIcon icon={faCoffee} /> },
  { icon: <FontAwesomeIcon icon={faFutbol} /> },
  { icon: <FontAwesomeIcon icon={faBug} /> },
  { icon: <FontAwesomeIcon icon={faSnowflake} /> },
  { icon: <FontAwesomeIcon icon={faTurkishLiraSign} /> },
  { icon: <FontAwesomeIcon icon={faMoon} /> },
  { icon: <FontAwesomeIcon icon={faHandSpock} /> },
  { icon: <FontAwesomeIcon icon={faSun} /> },
  { icon: <FontAwesomeIcon icon={faFlask} /> },
  { icon: <FontAwesomeIcon icon={faAnchor} /> },
  { icon: <FontAwesomeIcon icon={faMicrophone} /> },
  { icon: <FontAwesomeIcon icon={faMobile} /> },
  { icon: <FontAwesomeIcon icon={faFaceSmile} /> },
  { icon: <FontAwesomeIcon icon={faCar} /> },
  { icon: <FontAwesomeIcon icon={faTree} /> },
  { icon: <FontAwesomeIcon icon={faBicycle} /> },
  { icon: <FontAwesomeIcon icon={faHouse} /> },
  { icon: <FontAwesomeIcon icon={faCloud} /> },
];
